export const CONFIG = {
  ADMIN_WHATSAPP_NUMBER: '919838841695', // Format: Country code followed by 10 digit number (no +, -, or spaces)
  COMPANY_NAME: 'GharPeFix',
  TAGLINE: 'Professional Home Services At Your Doorstep',
  SUPPORT_EMAIL: 'support@gharpefix.com',
  OPERATING_HOURS: '8:00 AM - 9:00 PM (Everyday)',
  // EmailJS Configuration - User can enter actual keys here
  EMAILJS_SERVICE_ID: 'YOUR_SERVICE_ID', 
  EMAILJS_TEMPLATE_ID: 'YOUR_TEMPLATE_ID',
  EMAILJS_PUBLIC_KEY: 'YOUR_PUBLIC_KEY',
};

export const SERVICES = [
  // Electrical Services
  {
    id: 'electrician',
    name: 'General Electrician',
    category: 'Electrical',
    description: 'Diagnose and fix general electrical faults, wiring hazards, and power outages.',
    iconName: 'Zap',
    basePrice: '₹149',
    rating: '4.8',
    image: 'https://images.pexels.com/photos/8005397/pexels-photo-8005397.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'house-wiring',
    name: 'House Wiring',
    category: 'Electrical',
    description: 'Complete new wiring installation, casing-capping repair, or circuit setup.',
    iconName: 'Cable',
    basePrice: '₹499',
    rating: '4.9',
    image: 'https://images.pexels.com/photos/8005368/pexels-photo-8005368.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'switchboard-repair',
    name: 'Switch Board Repair',
    category: 'Electrical',
    description: 'Fix sparking switches, socket replacement, panel repair or new installations.',
    iconName: 'Sliders',
    basePrice: '₹99',
    rating: '4.7',
    image: 'https://images.pexels.com/photos/3862632/pexels-photo-3862632.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'inverter-installation',
    name: 'Inverter Installation',
    category: 'Electrical',
    description: 'Setup and wiring for new inverters and batteries with proper overload safety.',
    iconName: 'BatteryCharging',
    basePrice: '₹399',
    rating: '4.9',
    image: 'https://images.pexels.com/photos/6077368/pexels-photo-6077368.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'inverter-repair',
    name: 'Inverter Repair',
    category: 'Electrical',
    description: 'Troubleshoot backup failures, battery water topping, charging faults, and terminal cleanup.',
    iconName: 'Sliders',
    basePrice: '₹249',
    rating: '4.7',
    image: 'https://images.pexels.com/photos/3862613/pexels-photo-3862613.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  
  // Appliance Repair & Services
  {
    id: 'fan-repair',
    name: 'Fan Repair',
    category: 'Appliances',
    description: 'Fix speed issues, capacitor replacement, noise reduction, and general diagnostics.',
    iconName: 'Wind',
    basePrice: '₹129',
    rating: '4.7',
    image: 'https://images.pexels.com/photos/1076583/pexels-photo-1076583.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'ceiling-fan-installation',
    name: 'Ceiling Fan Installation',
    category: 'Appliances',
    description: 'Assembling and mounting of new ceiling fans with solid downrod alignment.',
    iconName: 'Wind',
    basePrice: '₹149',
    rating: '4.8',
    image: 'https://images.pexels.com/photos/3773571/pexels-photo-3773571.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'cooler-repair',
    name: 'Cooler Repair',
    category: 'Appliances',
    description: 'Pump replacement, motor check, grass pad changes, and internal cleaning.',
    iconName: 'Snowflake',
    basePrice: '₹249',
    rating: '4.6',
    image: 'https://images.pexels.com/photos/6444258/pexels-photo-6444258.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'desert-cooler-repair',
    name: 'Desert Cooler Repair',
    category: 'Appliances',
    description: 'Heavy duty motor rewinding, fan blade realignment, and chassis painting.',
    iconName: 'Snowflake',
    basePrice: '₹299',
    rating: '4.7',
    image: 'https://images.pexels.com/photos/6444261/pexels-photo-6444261.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'fridge-repair',
    name: 'Fridge Repair',
    category: 'Appliances',
    description: 'Fix cooling issues, thermostat failures, sensor errors, and door gasket checks.',
    iconName: 'CupSoda',
    basePrice: '₹349',
    rating: '4.8',
    image: 'https://images.pexels.com/photos/5824519/pexels-photo-5824519.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'refrigerator-gas-filling',
    name: 'Refrigerator Gas Filling',
    category: 'Appliances',
    description: 'Compressor check, vacuuming, copper tube leak test, and R134a/R600a gas top-up.',
    iconName: 'CupSoda',
    basePrice: '₹899',
    rating: '4.9',
    image: 'https://images.pexels.com/photos/5824534/pexels-photo-5824534.jpeg?auto=compress&cs=tinysrgb&w=600',
  },

  // Plumbing Services
  {
    id: 'plumbing',
    name: 'General Plumbing',
    category: 'Plumbing',
    description: 'Fix choked pipes, bathroom blockages, drainage cleanup, and system health checks.',
    iconName: 'Wrench',
    basePrice: '₹149',
    rating: '4.7',
    image: 'https://images.pexels.com/photos/6419128/pexels-photo-6419128.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'pipe-fitting',
    name: 'Pipe Fitting',
    category: 'Plumbing',
    description: 'Replace internal or external CPVC/UPVC pipe lines with leak-proof fittings.',
    iconName: 'Pipette',
    basePrice: '₹299',
    rating: '4.8',
    image: 'https://images.pexels.com/photos/6419130/pexels-photo-6419130.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'tap-installation',
    name: 'Tap Installation',
    category: 'Plumbing',
    description: 'Mount and connect bathroom taps, sink faucets, mixers, and health faucets.',
    iconName: 'Droplet',
    basePrice: '₹89',
    rating: '4.9',
    image: 'https://images.pexels.com/photos/6419122/pexels-photo-6419122.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'water-leakage-repair',
    name: 'Water Leakage Repair',
    category: 'Plumbing',
    description: 'Detect and resolve pipe leaks, joint seepage, and wall dampness issues.',
    iconName: 'ShieldAlert',
    basePrice: '₹199',
    rating: '4.7',
    image: 'https://images.pexels.com/photos/6419127/pexels-photo-6419127.jpeg?auto=compress&cs=tinysrgb&w=600',
  },

  // Water Systems
  {
    id: 'water-motor-installation',
    name: 'Water Motor Installation',
    category: 'Water Systems',
    description: 'Secure placement and wiring connection of monoblock or submersible water pumps.',
    iconName: 'Cog',
    basePrice: '₹599',
    rating: '4.9',
    image: 'https://images.pexels.com/photos/6077326/pexels-photo-6077326.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'water-motor-repair',
    name: 'Water Motor Repair',
    category: 'Water Systems',
    description: 'Fix motor startup failure, capacitor faults, worn bearings, and priming issues.',
    iconName: 'Settings',
    basePrice: '₹399',
    rating: '4.6',
    image: 'https://images.pexels.com/photos/6077351/pexels-photo-6077351.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'water-tank-connection',
    name: 'Water Tank Connection',
    category: 'Water Systems',
    description: 'Inlet/outlet connection fitting, air pipe setting, and overflow bypass installation.',
    iconName: 'Database',
    basePrice: '₹499',
    rating: '4.8',
    image: 'https://images.pexels.com/photos/6077370/pexels-photo-6077370.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'ro-installation',
    name: 'RO Installation',
    category: 'Water Systems',
    description: 'Wall-mounting of new reverse osmosis systems, pre-filter and drainage alignments.',
    iconName: 'Filter',
    basePrice: '₹349',
    rating: '4.9',
    image: 'https://images.pexels.com/photos/6444267/pexels-photo-6444267.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'ro-repair',
    name: 'RO Repair',
    category: 'Water Systems',
    description: 'Troubleshoot filter membrane blockages, booster pump faults, and low TDS values.',
    iconName: 'Filter',
    basePrice: '₹249',
    rating: '4.7',
    image: 'https://images.pexels.com/photos/6444263/pexels-photo-6444263.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
];
